services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: winbit_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - winbit_pgdata:/var/lib/postgresql/data

volumes:
  winbit_pgdata:
